# Generated by Django 3.0.7 on 2021-05-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210525_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskwork',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='taskwork',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
