# Generated by Django 3.0.7 on 2021-05-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskwork',
            old_name='text',
            new_name='taskleft',
        ),
    ]
