# Generated by Django 3.0.7 on 2021-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210525_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskwork',
            name='date_added',
            field=models.DateField(blank=True, verbose_name='Expected Task Completion Date(mm/dd/yyyy)'),
        ),
    ]
