# Generated by Django 3.0.7 on 2021-05-25 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210525_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskwork',
            name='datecomp',
        ),
        migrations.AddField(
            model_name='taskwork',
            name='date_added',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Expected Task Completion Date(mm/dd/yyyy)'),
            preserve_default=False,
        ),
    ]
